import { IndexHtmlTransformContext, Plugin } from "vite";
import { OutputAsset, OutputBundle, OutputChunk } from "rollup";
import { Input, InputAction, InputType, Packer } from "roadroller";
import CleanCSS from "clean-css";
import htmlMinify from "html-minifier";
import path from "path";
import fs from "fs/promises";

export default function roadrollerPlugin(): Plugin {
    return {
        name: "vite:roadroller",
        transformIndexHtml: {
            order: "post",
            handler: roadrollerHandler,
        },
    };
}

async function roadrollerHandler(
    html: string,
    ctx: IndexHtmlTransformContext,
): Promise<string> {
    const options = {
        includeAutoGeneratedTags: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
        collapseWhitespace: true,
        collapseInlineTagWhitespace: true,
        removeEmptyAttributes: true,
        removeOptionalTags: true,
        sortAttributes: true,
        minifyCSS: true,
    };

    const bundleOutputs = Object.values(ctx.bundle as OutputBundle);
    const javascript = bundleOutputs.find((output) =>
        output.fileName.endsWith(".js"),
    ) as OutputChunk | undefined;
    const css = bundleOutputs.find((output) =>
        output.fileName.endsWith(".css"),
    ) as OutputAsset | undefined;

    bundleOutputs
        .filter((output) => output !== javascript && output !== css)
        .forEach((output) =>
            console.warn(`WARN Asset not inlined: ${output.fileName}`),
        );

    if (css !== undefined) {
        html = embedCss(html, css);
    }

    html = await htmlMinify.minify(html, options);

    if (javascript !== undefined) {
        html = await embedJs(html, javascript);
    }

    return html;
}

/**
 * Embeds CSS into the HTML.
 * @param html The original HTML.
 * @param asset The CSS asset.
 * @returns The transformed HTML with the CSS embedded.
 */
function embedCss(html: string, asset: OutputAsset): string {
    const code = new CleanCSS({ level: 2 }).minify(
        asset.source as string,
    ).styles;

    let tag;
    if (code.length > 0) {
        tag = `<style>${code}</style>`;
    } else {
        tag = "";
    }

    const cssRegEx = new RegExp(
        `<link rel="stylesheet"[^>]*?href="[\./]*${asset.fileName}"[^>]*?>`,
    );
    return html.replace(cssRegEx, tag);
}

/**
 * Transforms the given JavaScript code into a packed version.
 * @param html The original HTML.
 * @param chunk The JavaScript output chunk from Rollup/Vite.
 * @returns The transformed HTML with the JavaScript embedded.
 */
async function embedJs(html: string, chunk: OutputChunk): Promise<string> {
    const scriptRegEx = new RegExp(
        `<script[^>]*?src=[\./]*${chunk.fileName}[^>]*?></script>`,
    );
    const removedTag = html.replace(scriptRegEx, "");

    let htmlInJs;
    if (removedTag.length > 0) {
        htmlInJs = `document.write("${removedTag}");` + chunk.code.trim();
    } else {
        htmlInJs = chunk.code.trim();
    }

    let packer = await createPacker(htmlInJs);

    await fs.mkdir(path.join(__dirname, "dist"), { recursive: true });
    await fs.writeFile(path.join(__dirname, "dist/output.js"), htmlInJs);

    const { firstLine, secondLine } = packer.makeDecoder();

    const uncompressedScript = `<script>${htmlInJs}</script>`;
    const compressedScript = `<script>${firstLine}${secondLine}</script>`;

    if (uncompressedScript.length <= compressedScript.length) {
        return uncompressedScript;
    } else {
        return compressedScript;
    }
}

async function createPacker(htmlInJs: string): Promise<Packer> {
    const inputs: Input[] = [
        {
            data: htmlInJs,
            type: "js" as InputType,
            action: "eval" as InputAction,
        },
    ];

    let packer: Packer;
    if (process.env.USE_RR_CONFIG) {
        packer = await loadPackerFromConfig(inputs);
    } else {
        packer = new Packer(inputs, { allowFreeVars: true });
        await packer.optimize(2);
    }

    return packer;
}

async function loadPackerFromConfig(inputs: Input[]): Promise<Packer> {
    let options;

    try {
        options = JSON.parse(
            await fs.readFile(
                path.join(__dirname, "roadrollerConfig.json"),
                "utf-8",
            ),
        );
    } catch (_) {
        throw new Error(
            "Roadroller config not found. Use 'npm run find-best' to generate one.",
        );
    }

    return new Packer(inputs, options);
}
